name: Installation precess testing

on:
  push:
    branches:
      - tmp
jobs:
  curl_download_on_centOS:
    runs-on: ubuntu-latest
    name: curl download on CentOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run commands on CentOS 8
        run: |
          docker pull centos:centos8.4.2105
          docker run --rm -v $PWD:/workdir -w /workdir centos:8 bash -c "
            rm -rf /etc/yum.repos.d/*
            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
            cat /etc/yum.repos.d/CentOS-Base.repo 
            yum install -y git
            cd; mkdir tmp; cd tmp
            sh -c \"$(curl -fsSL https://raw.githubusercontent.com/wuchuheng/dotfiles/tmp/src/tools/install.sh)\"
            ls -ahl
          "