name: Installation precess testing

on:
  push:
    branches:
      - tmp
jobs:
  curl_download_on_ubuntu:
    runs-on: ubuntu-latest
    name: "Download: download dotfiles by curl on Ubuntu"
    steps:
      - name: Run commands on Ubuntu
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/wuchuheng/dotfiles/tmp/src/tools/install.sh)"
