name: Installation precess testing

on:
  push:
    branches:
      - tmp
jobs:
  curl_download_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run commands on Ubuntu
        run: |
          curl 
