name: Release

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: fetch all submodule
        run: git submodule update --init
      - name: Set tar file name
        id: vars
        run: |
          projectName=$(basename $PWD)
          echo "TAR_FILE=${projectName}-${GITHUB_REF#refs/tags/}.tar.gz" >> $GITHUB_ENV
          echo "ZIP_FILE=${projectName}-${GITHUB_REF#refs/tags/}.zip" >> $GITHUB_ENV

      - name: Create Release Archive
        run: |
          tarFile=../${TAR_FILE}
          tar -zcvf ${tarFile} .
          zipFile=../${ZIP_FILE}
          zip -r ${zipFile} ./
          mv ${zipFile} .
          mv ${tarFile} .
      - name: Set change log
        run: |
          echo "version: ${GITHUB_REF#refs/tags/}"
          .github/workflows/get_change_log.sh "${GITHUB_REF#refs/tags/}" > tmp.log
          cat tmp.log
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.TAR_FILE }},${{ env.ZIP_FILE }}"
          bodyFile: "tmp.log"
